apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  labels:
    azure.workload.identity/use: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ai-wi-sa
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "azure.workload.identity/use"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: ai
        image: forbeeregistry.azurecr.io/ai:v3
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        envFrom:
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "3Gi"
            cpu: "1"
        ports:
        - containerPort: 8083
        readinessProbe:
          httpGet:
            path: '/actuator/health/readiness'
            port: 8083
          initialDelaySeconds: 180
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: '/actuator/health/liveness'
            port: 8083
          initialDelaySeconds: 180
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 5
      - name: python
        image: forbeeregistry.azurecr.io/python:v3
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-kafka:9092"
        - name: KAFKA_TOPIC
          value: "forbee"
        envFrom:
          - secretRef:
              name: app-secrets
        ports:
        - containerPort: 8003

# 파이썬 readiness, liveness 프로브는 main.py에도 설정해야 함
