apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  labels:
    azure.workload.identity/use: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ai-wi-sa
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "azure.workload.identity/use"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: ai
        image: forbeeregistry.azurecr.io/ai:latest
        env:
        - name: AZURE_CLIENT_ID
          value: "67c8e9d2-4e62-4a58-87e7-c74c258163e5"
        ports:
        - containerPort: 8083
        readinessProbe:
          httpGet:
            path: '/actuator/health/readiness'
            port: 8083
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: '/actuator/health/liveness'
            port: 8083
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 5
      - name: fastapi
        image: forbeeregistry.azurecr.io/fastapi:latest
        env:
        - name: AZURE_CLIENT_ID
          value: "67c8e9d2-4e62-4a58-87e7-c74c258163e5"
        envFrom:
          - secretRef:
              name: app-secrets
        ports:
        - containerPort: 8003

# 파이썬 readiness, liveness 프로브는 main.py에도 설정해야 함
