apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
      - name: ai
        image: <YOUR_ACR_SERVER>.azurecr.io/ai:latest
        ports:
        - containerPort: 8083
        readinessProbe:
          httpGet:
            path: '/actuator/health/readiness'
            port: 8083
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: '/actuator/health/liveness'
            port: 8083
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 5
      - name: fastapi
        image: <YOUR_ACR_SERVER>.azurecr.io/fastapi:latest
        ports:
        - containerPort: 8003

# 파이썬 readiness, liveness 프로브는 main.py에도 설정해야 함
