apiVersion: apps/v1
kind: Deployment
metadata:
  name: community
  labels:
    app: community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community
  template:
    metadata:
      labels:
        app: community
    spec:
      containers:
        - name: community
          image: forbeeregistry.azurecr.io/community:08201358
          ports:
            - containerPort: 8080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-key-secret
                  key: AZURE_STORAGE_KEY
          # readinessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 10
          # livenessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 5
