tasks:
  - name: Start Spring Boot & FastAPI
    command: |
      cd chatbot
      mvn spring-boot:run &
      cd ../chatbot_ai
      uvicorn main:app --host 0.0.0.0 --port 8002

  - name: Install Azure
    before:
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

  - name: Install kubectl
    before: |
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

ports:
  - port: 8082
    onOpen: open-preview
  - port: 8002
    onOpen: open-preview

env:
  OPENAI_API_KEY: ${OPENAI_API_KEY}