apiVersion: apps/v1
kind: Deployment
metadata:
  name: aimap
  labels:
    app: aimap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aimap
  template:
    metadata:
      labels:
        app: aimap
    spec:
      containers:
        - name: aimap
          image: forbeeregistry.azurecr.io/aimap:08251141
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SGIS_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: sgis-api-keys
                  key: SGIS_CONSUMER_KEY
            - name: SGIS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sgis-api-keys
                  key: SGIS_SECRET_KEY
      imagePullSecrets: # Add this section
        - name: acr-secret # Name of your image pull secret
