server:
  port: 8088

---

spring:
  profiles: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/.well-known/jwks.json
  cloud:
    gateway:
      routes:
         - id: community-posts
           uri: http://localhost:8085
           predicates:
            - Path=/posts/**
         - id: community-comments
           uri: http://localhost:8085
           predicates:
            - Path=/comments/**
         - id: ai-map
           uri: http://localhost:8081
           predicates:
            - Path=/maps/**
         - id: tree
           uri: http://localhost:8087
           predicates:
            - Path=/plants/**
         - id: user
           uri: http://localhost:8084
           predicates:
            - Path=/users/**
         - id: memberRequest
           uri: http://localhost:8084
           predicates:
            - Path=/memberRequestLists/**
         - id: file
           uri: http://localhost:8084
           predicates:
            - Path=/files/**

        #  - id: dashboard
        #    uri: http://localhost:0
        #    predicates:
        #     - Path=/maps/**
         # 챗봇
         - id: chatbot
           uri: http://localhost:8082
           predicates:
            - Path=/chatbots/**

         # Spring → FastAPI 프록시
         - id: chat_to_spring
           uri: http://127.0.0.1:8082
           predicates:
            - Path=/chatbot/chat
            - Method=POST

         - id: health_to_spring
           uri: http://127.0.0.1:8082
           predicates:
            - Path=/chatbot/health
            - Method=GET

         # FastAPI
         - id: help_to_fastapi
           uri: http://127.0.0.1:8002
           predicates:
            - Path=/chatbot/help
            - Method=POST

         - id: health_fastapi
           uri: http://127.0.0.1:8002
           predicates:
            - Path=/chatbot/health-fast
            - Method=GET
         - id: ai
           uri: http://localhost:8083
           predicates:
            - Path=/ai/**, /api/**
         - id: oauth-register
           uri: http://localhost:8090
           predicates:
            - Path=/oauth/users/register
         - id: oauth-token
           uri: http://localhost:8090
           predicates:
            - Path=/oauth/token
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://oauth:8080/.well-known/jwks.json
  cloud:
    gateway:
      routes:
         - id: community-posts
           uri: http://community:8080
           predicates:
            - Path=/posts/**

         - id: community-comments
           uri: http://community:8080
           predicates:
            - Path=/comments/**

         - id: user
           uri: http://user:8080
           predicates:
            - Path=/users/**

         - id: memberRequest
           uri: http://user:8080
           predicates:
            - Path=/memberRequestLists/**

         - id: file
           uri: http://user:8080
           predicates:
            - Path=/files/**

         - id: milwon-application
           uri: http://user:8080
           predicates:
            - Path=/trees/**

         - id: plants
           uri: http://tree:8080
           predicates:
            - Path=/plants/**

         - id: oauth-register
           uri: http://oauth:8080
           predicates:
            - Path=/oauth/users/register

         - id: oauth-token
           uri: http://oauth:8080
           predicates:
            - Path=/oauth/token      

         - id: ai
           uri: http://ai:8080
           predicates:
            - Path=/ai/**, /api/**

         # 챗봇
         - id: chatbot
           uri: http://chatbot:8080
           predicates:
            - Path=/chatbots/**

         # Spring → FastAPI 프록시
         - id: chat_to_spring
           uri: http://chatbot:8080
           predicates:
            - Path=/chatbot/chat
            - Method=POST

         - id: health_to_spring
           uri: http://chatbot:8080
           predicates:
            - Path=/chatbot/health
            - Method=GET

         # FastAPI
         - id: help_to_fastapi
           uri: http://chatbot-ai:8000
           predicates:
            - Path=/chatbot/help
            - Method=POST

         - id: health_fastapi
           uri: http://chatbot-ai:8000
           predicates:
            - Path=/chatbot/health-fast
            - Method=GET

         - id: aiMap
           uri: http://aimap:8080
           predicates:
           - Path=/maps/**

         - id: frontend2
           uri: http://frontend2:80
           predicates:
            - Path=/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080