server:
  port: 8088

---

spring:
  profiles: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/.well-known/jwks.json
  cloud:
    gateway:
      routes:
         - id: community-posts
           uri: http://localhost:8085
           predicates:
            - Path=/posts/**
         - id: community-comments
           uri: http://localhost:8085
           predicates:
            - Path=/comments/**
         - id: ai-map
           uri: http://localhost:8081
           predicates:
            - Path=/predict-and-get-info
         - id: tree
           uri: http://localhost:0
           predicates:
            - Path=/plants/**
         - id: user
           uri: http://localhost:8084
           predicates:
            - Path=/users/**
         - id: dashboard
           uri: http://localhost:0
           predicates:
            - Path=/maps/**
         - id: chatbot
           uri: http://localhost:0
           predicates:
            - Path=/chatbots/**
         - id: ai
           uri: http://localhost:8083
           predicates:
            - Path=/ai/**, /api/**
         - id: oauth-register
           uri: http://localhost:8090
           predicates:
            - Path=/oauth/users/register
         - id: oauth-token
           uri: http://localhost:8090
           predicates:
            - Path=/oauth/token
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://oauth:8080/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: community
          uri: http://community:8080
          predicates:
            - Path=/posts/**/comments/**//**//** 
        - id: tree
          uri: http://tree:8080
          predicates:
            - Path=/plants/** 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**/memberRequestLists/** 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path= /maps/**
        - id: chatbot
          uri: http://chatbot:8080
          predicates:
            - Path=/chatbots/** 
        - id: ai
          uri: http://ai:8080
          predicates:
            - Path=/ai/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
