<<<<<<< HEAD:aiMap/src/main/resources/application.yml
spring:
  config:
    activate:
      on-profile: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/master/protocol/openid-connect/certs
=======
server:
  port: 8085

spring:
  application:
    name: community

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---
spring:
  profiles: default
>>>>>>> origin/feat/frontend/community:community/src/main/resources/application.yml
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
<<<<<<< HEAD:aiMap/src/main/resources/application.yml
          group: aiMap
=======
          group: community
>>>>>>> origin/feat/frontend/community:community/src/main/resources/application.yml
          destination: forbee
          contentType: application/json
        event-out:
          destination: forbee
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
    org.springframework.web: DEBUG
    org.springframework.http.converter: TRACE

<<<<<<< HEAD:aiMap/src/main/resources/application.yml
server:
  port: 8081
=======
api:
  url:
    community: localhost:8082

server:
  port: 8085
>>>>>>> origin/feat/frontend/community:community/src/main/resources/application.yml

---
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/master/protocol/openid-connect/certs
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: aiMap
          destination: forbee
          contentType: application/json
        event-out:
          destination: forbee
<<<<<<< HEAD:aiMap/src/main/resources/application.yml
          contentType: application/json
=======
          contentType: application/json

api:
  url:
    community: community:8080
>>>>>>> origin/feat/frontend/community:community/src/main/resources/application.yml
