server:
  port: 8082

spring:
  main:
    allow-bean-definition-overriding: true

fastapi:
  url: ${FASTAPI_URL:http://localhost:8000}

azure:
  storage:
    account-url: ${AZURE_STORAGE_ACCOUNT_URL:https://aivle26storage.blob.core.windows.net}
    container-name: ${AZURE_CONTAINER_NAME:container}

logging:
  level:
    root: INFO
