server:
  port: 8083

# management:
#   endpoints:
#     web:
#       exposure:
#         include: env,health,info

---

spring:
  config:
    activate:
      on-profile: default
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://forbee-ai-db.mysql.database.azure.com:3306/ai?useSSL=true&requireSSL=false
    username: forbeeai
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ai
      auto-offset-reset: earliest
    # listener:
    #   auto-startup: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/master/protocol/openid-connect/certs

  # cloud:
  #   stream:
  #     kafka:
  #       binder:
  #         brokers: localhost:9092
  #       streams:
  #         binder:
  #           configuration:
  #             default:
  #               key:
  #                 serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  #               value:
  #                 serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  #     bindings:
  #       event-in:
  #         group: ai
  #         destination: forbee
  #         contentType: application/json
  #       event-out:
  #         destination: forbee
  #         contentType: application/json

azure:
  storage:
    account-url: ${AZURE_STORAGE_ACCOUNT_URL:https://forbee.blob.core.windows.net}
    container-name: ${AZURE_CONTAINER_NAME:blob}

logging:
  level:
    root: INFO
    org.hibernate.type: trace
    org.springframework.cloud: debug

---

spring:
  config:  
    activate:
      on-profile: docker
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://forbee-ai-db.mysql.database.azure.com:3306/ai?useSSL=true&requireSSL=false
    username: forbeeai
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  kafka:
  #   # bootstrap-servers: localhost:9092  # kafka:9092 였음 default profile이 실행되지 않아서 localhost로 변경
    bootstrap-servers: my-kafka:9092  # AKS 배포 시 사용
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/master/protocol/openid-connect/certs
          # jwk-set-uri: http://oauth:9090/
  # cloud:
  #   stream:
  #     kafka:
  #       binder:
  #         brokers: my-kafka:9092
  #       streams:
  #         binder:
  #           configuration:
  #             default:
  #               key:
  #                 serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  #               value:
  #                 serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  #     bindings:
  #       event-in:
  #         group: ai
  #         destination: forbee
  #         contentType: application/json
  #       event-out:
  #         destination: forbee
  #         contentType: application/json

fastapi:
  url: http://localhost:8003

azure:
  storage:
    account-url: https://forbee.blob.core.windows.net
    container-name: blob

    # AKS 액세스 키 인증 때문에 추가
    account-key: ${AZURE_STORAGE_ACCESS_KEY}
    account-name: forbee

logging:
  level:
    root: INFO
    # org.hibernate.type: trace
    # org.springframework.cloud: debug