apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: forbeeregistry.azurecr.io/user:08200147
          ports:
            - containerPort: 8080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret # Name of your DB Secret
                  key: DB_PASSWORD # Key within the Secret
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secret # Name of your Azure Storage Secret
                  key: AZURE_STORAGE_CONNECTION_STRING # Key within the Secret
          # readinessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 10
          # livenessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 5
      imagePullSecrets: # Add this section
        - name: acr-secret # Name of your image pull secret
